theme: "minima"

title: "Paul Naughton's Blog"
author: "Paul Naughton"
description: "A personal blog, mostly covering PowerShell related themes."

# Email / Social media user names used by the minima theme:
github_username: "pauljnav"
email: "tecknikp@gmail.com"
twitter_username: "twitteruser"
linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################

#rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

header_pages:
  - archive.md
  - bookmarks.md
  - acknowledgements.md
  - _references\references.md

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
